[package]
name = "awto-macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
bae = { path = "../../bae/bae" }
heck = "0.3"
paste = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "parsing"] }
